### ISSUE TITLE
Config does not work

### ISSUE THREAD

**Issue by frereit** [zack6849/MaintenanceMode#1]
Hi! I am changing the Config of the Plugin LockDown, but when i reload/restart my server, it resets. Plugin Version: 1.6.2, Spigot 1.8.8

**Comment by zack6849** [comment]
Changes to the configuration need to be made while the server is shut off, or you type in /reload to make sure it loads the new settings.

If you change a file and the plugin isn't aware of it, it just will save what it knows are currently the settings it should have

**Comment by frereit** [comment]
`

Changes to the configuration need to be made while the server is shut off, or you type in /reload to make sure it loads the new settings.

If you change a file and the plugin isn't aware of it, it just will save what it knows are currently the settings it should have
`

THX! When I save it and do /reload it overwrites again... When i stop the server and edit then, it works. I think it is because you wrote saveConfig(); in the onDisable function. Maybe remove that and only save the Config when you edited it in the plugin. But REALLY a very good plugin! I love it! Thanks!
